[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'rm -rf node_modules/.cache',
  'npm ci --omit=dev --cache /tmp/npm-cache'
]

[start]
cmd = 'npm start'

[variables]
NPM_CONFIG_CACHE = '/tmp/npm-cache'